Repository IPARI-282/teum, pull requests merged in 2025-04, with the labels that each got.

#6 [IP-2] PR 템플릿 추가, PR 커밋 추가 시에도 github action 실행되도록 처리
  .github/actions/assignReviewer/assignReviewer.mjs
  .github/pull_request_template.md
  .github/workflows/assign_reviewer.yml
  README.md
Labels: 🤖 기능 추가

#7 [IP-4] 프로젝트 초기 폴더 구조 세팅
  .gitignore
  teum.xcodeproj/project.pbxproj
  teum/Application/Appdelegate.swift
  teum/Application/Scenedelegate.swift
  teum/Application/teumApp.swift
  teum/Coordinator/AppCordinator.swift
  teum/Extension/Colors+.swift
  teum/Manager/NetworkManager.swift
  teum/Model/User.swift
  teum/Protocol/ViewModelType.swift
  teum/Resource/Assets/Assets.xcassets/AccentColor.colorset/Contents.json
  teum/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  teum/Resource/Assets/Assets.xcassets/Contents.json
  teum/Resource/Colors/Colors.swift
  teum/Resource/Fonts/Fonts.swift
  teum/Utils/someModifier.swift
  teum/Views/Community/CommunityView.swift
  teum/Views/Community/CommunityViewModel.swift
  teum/Views/Login/LoginView.swift
  teum/Views/Login/LoginViewModel.swift
  teum/Views/LookingForTeum/LookingForTeumView.swift
  teum/Views/LookingForTeum/LookingForTeumViewModel.swift
  teum/Views/MyPage/MyPageView.swift
  teum/Views/MyPage/MyPageViewModel.swift
  teum/Views/TeumNote/TeumNoteView.swift
  teum/Views/TeumNote/TeumNoteViewModel.swift
Labels: 🤖 기능 추가

#12 [IP-17] 틈 노트 작성 화면 UI 구현, Firebase 임시 연결, Github Actions 수정
  .github/actions/assignReviewer/assignReviewer.mjs
  teum/Manager/UserDefaultsManager.swift
  teum/Model/Note.swift
  teum/Views/TeumNote/FlipCard.swift
  teum/Views/TeumNote/TestView.swift
  teum/Views/TeumNote/TeumNoteWriteView.swift
Labels: 🎨 디자인

#13 [IP-18] 틈 노트 작성 화면 변경, 틈 노트 화면 플로팅 버튼 추가
  teum.xcodeproj/project.pbxproj
  teum/ContentView.swift
  teum/Manager/UserDefaultsManager.swift
  teum/Model/Note.swift
  teum/Views/TeumNote/FlipCard.swift
  teum/Views/TeumNote/TestView.swift
  teum/Views/TeumNote/TeumNoteView.swift
  teum/Views/TeumNote/TeumNoteWriteView.swift
Labels: 🤖 기능 추가

#14 [Fix] Note 데이터 모델 및 Coordinator 적용 및 수정
  teum.xcodeproj/project.pbxproj
  teum/Application/teumApp.swift
  teum/ContentView.swift
  teum/Coordinator/AppCordinator.swift
  teum/GoogleService-Info.plist
  teum/Info.plist
  teum/Model/Note.swift
  teum/Protocol/ViewModelType.swift
  teum/Views/Community/CommunityDetailView.swift
  teum/Views/Community/CommunityView.swift
  teum/Views/Community/CommunityViewModel.swift
  teum/Views/TeumNote/TestView.swift
  teum/Views/TeumNote/TeumNoteView.swift
  teum/Views/TeumNote/TeumNoteViewModel.swift
  teum/Views/TeumNote/TeumNoteWriteView.swift
Labels: 🎨 디자인

#18 [IP-19] 마이페이지 추가
  teum.xcodeproj/project.pbxproj
  teum/Extension/Colors+.swift
  teum/Manager/AppleLoginManager.swift
  teum/Views/Login/LoginView.swift
  teum/Views/Login/LoginViewModel.swift
  teum/Views/MyPage/MyPageView.swift
  teum/Views/TeumNote/TestView.swift
Labels: 🤖 기능 추가

#19 [Feat] 틈 노트 데이터 연결, 미사용 TestView 관련 코드 삭제, 마이페이지 버튼 Padding 수정
  teum.xcodeproj/project.pbxproj
  teum/ContentView.swift
  teum/Views/MyPage/MyPageView.swift
  teum/Views/TeumNote/FlipCard.swift
  teum/Views/TeumNote/TestView.swift
  teum/Views/TeumNote/TeumNoteView.swift
Labels: 🤖 기능 추가

#20 [IP-14] 틈 커뮤니티 뷰 구현
  teum.xcodeproj/project.pbxproj
  teum/Manager/FireStoreManager.swift
  teum/Resource/Assets/Assets.xcassets/AppIcon.appiconset/Contents.json
  teum/Resource/Assets/Assets.xcassets/AppIcon.appiconset/KakaoTalk_Photo_2025-04-28-21-38-23.png
  teum/Resource/Assets/Assets.xcassets/AppIconPreview.imageset/Contents.json
  teum/Resource/Assets/Assets.xcassets/AppIconPreview.imageset/KakaoTalk_Photo_2025-04-28-21-38-23 1.png
  teum/Resource/Assets/Assets.xcassets/AppIconPreview.imageset/KakaoTalk_Photo_2025-04-28-21-38-23 2.png
  teum/Resource/Assets/Assets.xcassets/AppIconPreview.imageset/KakaoTalk_Photo_2025-04-28-21-38-23.png
  teum/Resource/Assets/Assets.xcassets/ProfileImage.imageset/Contents.json
  teum/Resource/Assets/Assets.xcassets/ProfileImage.imageset/Image.png
  teum/Views/Community/CommunityView.swift
  teum/Views/Community/CommunityViewModel.swift
Labels: 🤖 기능 추가, 🎨 디자인
